### ISSUE TITLE
% cmake .                                                   gaoya@gaoya-MS-7A94 CMake Error: The current CMakeCache.txt directory /home/gaoya/Applications/network-ball-gtk/CMakeCache.txt is different than the directory /home/alonebo/CLionProjects/network-ball-gtk where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

### ISSUE THREAD

**Issue by ouening** [Baloneo/network-ball-gtk#1]
OS：Ubuntu18.04 
gcc：5.5

CMake Error: The current CMakeCache.txt directory /home/gaoya/Applications/network-ball-gtk/CMakeCache.txt is different than the directory /home/alonebo/CLionProjects/network-ball-gtk where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

**Comment by byte-voyager** [comment]
remove CMakeCache.txt
